language: ruby
rvm:
- 2.3.0
services:
- postgresql
before_script:
- psql -c 'create database legislated_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: QYKsgpbt9g27cPQMHmLp2mjvhfrNRQZF6AzWDOrgBEbZILI0LAr5lsSPbfUqxxlDTwLecpABBLi1GmLhMoncjzxQEdzXj0vFZIVoeG4SGShZ0J6z2V/G1bndDH+P7v9ykzICMAfzoJsZUW81ASPC+N35uE2djpu4+qE8OKPo6V+XiBf4xi0w+HWu8WIrdqIwT9os+kCgNZxjDYqslHbttySHo6jiGEtGDBC+UZFrzJ57gzH46lKZjjBkdZ16XCZN0pPjONVTUMJRSv9Jp/4w30hXP+Ckb95aXk11uWwWenWfHoBUR8/jz1lnvcXnLwjhFnfZ/bhlc3MUexxDknmAgmd9MTAdwqTwf4OuXmvOsHF5RI4tbyx4jZgjkvITcpnUx9OnvyF8CTfhUbY8hcboQvG38ndlKy0csCSkbWRx4ZqPzERCqeoLkyTpIKa0L7COB+MFYHhpS9AdgtR6JJb/OFw5DvkyjuLa52QEik+9tyK2zTTxOZRshIy5Gygnb38ISMlO6fKK5Qe66ojz87iUWEMUWVG4ctdnUDblmTFfPbxqbDOleCUsMmGr8GJ+YFvS1eN886TG+VW45fNr403AEK7yzTbuhGkyOSZ4Lq7oIj1lE10U0eMhqz/ihDPMAW87FCzThahtC+2OG0cCObfHaQzpU/IUzPzr47j/hK4UEWU=
  app:
    master: legislated-staging
