sudo: required
language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
env:
  - ADMIN_CREDENTIALS="Basic YWRtaW46cGFzc3dvcmTCow==" TZ=America/Chicago
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - production
install:
  - bundle --deployment
  - nvm install 8
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - psql -c 'create database legislated_test;' -U postgres
deploy:
  provider: heroku
  run: rake db:migrate
  api_key:
    secure: TonJd6LY2bK1BuOWmaVozYnS0dP1jqze4yE/nZnjjAtLLHeZwKV/cySJkWorM6NKjSWcX6J2IF0a5GIyjWYxdWB/2TJSNbkEASM/TQ/LNeYyuVThXpvDIqhF9FfEBn00e3AfWzWGZSQ17VvsMMiUjiUwCv+0hMh83S81m0+pCY9xCESPows7LEaARV0kAq/KAdgm9i5+UR73mRgGFijZBJ1D8HJ7ZZHQ+JnWRb77zeFqlSCeUNGq+ggFyZThKmWzU9McGsZcpeANR+tEKe4gF05i1sTX/nFWkJLhoYXmz1F4G6NImAcbIr6yl2GG+Cmt8qX0aKkb0pWowdLD2jlCWh/5FDmOShC1i7SnsEqPifHUvevw463yqG/V/VvqPh1igQkdKfI3HjO4gqBtPjYhLUVCOD3qifv9w8UgwX6kBAwPosKy8zJVXXw6/BBlMXmCl1Eg9rbF9q+y/jxNNr/Gyw/cEj0kQYGRwps2DkAyOnGc5Trx7M13kXrkJvx+MOna+JlRnRdpRuUryndmZMj5xaU0vRsPukZroc2nqpiXODcz4jKc9ubqqoA0xWaxvenH6pEFMYEyy4IIFgU6YpnTTqU7aQuf2JkBA2sb+tUUI3MwXtMKFTBqxtlysgckZxd8ezTDzqzIYX9Lh0h3mB6lz63NtkyHl52gl3uxb1WTnZI=
  app:
    master: legislated-staging
    production: legislated
addons:
  postgresql: '9.6'
