version: '3'
services:
  db:
    image: postgres:9.6
  rds:
    image: redis:4.0.10
  wpk:
    build: .
    command: './bin/webpack-dev-server'
    volumes:
      - .:/legislated
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: 'development'
      RAILS_ENV: 'development'
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'
  web:
    build: .
    volumes:
      - .:/legislated
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      PGHOST: 'db'
      PGUSER: 'postgres'
      PGDBNAME: 'legislated-development'
    depends_on:
      - db
      - rds
      - wpk
