version: '3.4'
x-app: &app
  build: .
  volumes:
    - .:/legislated
services:
  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  rds:
    image: redis:4.0.10
  wpk:
    <<: *app
    command: ./bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  web:
    <<: *app
    command: './bin/puma -C config/puma.rb'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    environment:
      REDIS_URL: 'redis://@rds'
      DATABASE_URL: 'postgres://postgres:@db:5432/legislated_development'
      WEBPACKER_DEV_SERVER_HOST: wpk
    depends_on:
      - db
      - rds
      - wpk
  wrk:
    <<: *app
    command: './bin/sidekiq'
    environment:
      REDIS_URL: 'redis://@rds'
      DATABASE_URL: 'postgres://postgres:@db:5432/legislated_development'
    depends_on:
      - db
      - rds
