version: '3'
services:
  db:
    image: postgres:9.6
  web:
    build: .
    volumes:
      - .:/legislated
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      PGHOST: 'db'
      PGUSER: 'postgres'
      PGDBNAME: 'legislated'
    depends_on:
      - db
