default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: legislated_development

test:
  <<: *default
  database: legislated_test

staging:
  <<: *default
  database: legislated_staging
  username: legislated
  password: <%= ENV['LEGISLATED_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: legislated_production
  username: legislated
  password: <%= ENV['LEGISLATED_DATABASE_PASSWORD'] %>
