default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['LEGISLATED_DATABASE_HOST'] %>
  username: <%= ENV['LEGISLATED_DATABASE_USER'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: legislated_development

test:
  <<: *default
  database: legislated_test

staging:
  <<: *default
  database: legislated_staging
  username: legislated
  password: <%= ENV['LEGISLATED_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: legislated_production
  username: legislated
  password: <%= ENV['LEGISLATED_DATABASE_PASSWORD'] %>
